### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by sdsy888** [TAMU-VITA/GLNet#12]
Hi @chenwydj , thank you for your work.

Since the competition link you provide is no longer reachable, could you provide a dataset split (train/crossvali/test) you use during training and validation?

Thank you!

**Comment by KiyoKando** [comment]
Hi, providing the training datasets privately is prohibited.
See the issue below.
https://github.com/TAMU-VITA/GLNet/issues/2

You can still request a dataset by signing up for a competition.
https://competitions.codalab.org/competitions/18468

Best.

**Comment by chenwydj** [comment]
I can open the link.
![Screen Shot 2019-10-24 at 11 25 05](https://user-images.githubusercontent.com/10953233/67505915-be7a9800-f651-11e9-8324-2bbebc81f24f.png)

For the Inria Aerial, we randomly split the whole dataset into 70%/15%/15% as train/validation/test.

**Comment by sdsy888** [comment]
> I can open the link.
> ![Screen Shot 2019-10-24 at 11 25 05](https://user-images.githubusercontent.com/10953233/67505915-be7a9800-f651-11e9-8324-2bbebc81f24f.png)
> 
> For the Inria Aerial, we randomly split the whole dataset into 70%/15%/15% as train/validation/test.

thank you. That's strange. I'll try agian.
