### ISSUE TITLE
A mistake in file train.txt last line

### ISSUE THREAD

**Issue by zhangbin0917** [TAMU-VITA/GLNet#13]
The last line in file `train.txt` is `sat.h`. I think it is a mistake, please revise it.

**Comment by chenwydj** [comment]
Thank you very much for pointing out this typo!

Seems that the `sat.h` comes with the official dataset,and the [line here](https://github.com/TAMU-VITA/GLNet/blob/a8132640772e4ed3f6ea29a3ab03dc467df2fb66/train_deep_globe.py#L45) will filter out non-image files. But anyway, I cleaned the `train.txt`.

**Comment by zhangbin0917** [comment]
I have another question.
Do you use the images in the 803 images except the train.txt and crossvali.txt files as test sets?

**Comment by chenwydj** [comment]
Yes, you are right.

I happen to upload the wrong file list for the validation. I just update the files.

**Comment by zhangbin0917** [comment]
Maybe also have some mistakes ?
In your paper, you write `We randomly split images into training, validation and testing sets with 455, 142, and 206 images respectively.`
But the number is Inconsistent in `train.txt`, `crossvali.txt` and `test.txt` which have 454, 207 and 142 images.

**Comment by chenwydj** [comment]
Thank you very much for your effort!

Yes in our experiments the #train/val/test are 454/207/142. We will update our arxiv version.
