### ISSUE TITLE
Fail at evaluating task on google colab

### ISSUE THREAD

**Issue by KiyoKando** [TAMU-VITA/GLNet#14]
Hi, thank you for your generous support and courage to open this valuable library on the web!
I've been trying to reproduce the result, but seem to fail at basic tasks on Colab.
I suppose it is an environmental issue, could you tell me what kind of environment did you use for this?

Is it enough GPUs for this task?
Gen RAM Free: 12.8 GB  | Proc size: 156.6 MB
GPU RAM Free: 11441MB | Used: 0MB | Util   0% | Total 11441MB

Before the bash, I separated the dataset into 3 directories like the way below,
so I think that the dataset is set in the right place.
GLNet
-datas
--data
----train
--------Sat(455)
--------Label(455)
----crossvali
--------Sat(207)
--------Label(207)
----offical_crossvali
--------Sat(142)
--------Label(142)
--runs
----fpn_deepglobe_global
--saved_models

Errors, when executed in google colab, are below.
-fail at train.sh
https://colab.research.google.com/drive/1WfeSE8zXAYQfCLIas6JxmP6eGFMx878a
-fail at eval.sh
https://colab.research.google.com/drive/1dBjlA26VJgfQjv7zUJAV0DrVAhQ3jG59

**Comment by chenwydj** [comment]
Hi KiyoKando! Thank you for your interest in our work!

0) For the memory and GPU: yes they are enough.
1) I ran training for mode 1 again and did not meet the issue you mentioned. Could you please confirm you are using the latest code?
2) I stopped after [this line](https://github.com/TAMU-VITA/GLNet/blob/master/helper.py#L305) and `outputs_global.size()` gives `torch.Size([6, 7, 127, 127])`, `labels_glb.size()` gives `torch.Size([6, 127, 127])`
3) I stopped after [this line](https://github.com/TAMU-VITA/GLNet/blob/master/utils/loss.py#L56) and both `probs.size()` and `target.size()` gives `torch.Size([96774, 7])`, where 96774 = 6 * 127 * 127. Your 290322 = 3 * 96774

Could you check if you can get the same sizes as I mentioned in (2) and (3)?

For the evaluation error, you could try to set the works to 0 in [this line](https://github.com/TAMU-VITA/GLNet/blob/a8132640772e4ed3f6ea29a3ab03dc467df2fb66/train_deep_globe.py#L53).

**Comment by KiyoKando** [comment]
Thanks for your generous support and patience.
Still struggling to utilize this code to public service purpose.

1. My code is pulled from your repository on 10/23 and datasets are separated by your recent update.

2-3. Thank you for your kind guide but since I use google co-lab, I still could not find how to make a breakpoint and check inside the variables, yet.
Could it possible for you to tell us what kind of environment do you use for this?

In addition, I changed the workers = 10 -> workers = 0 like below,
dataloader_val = torch.utils.data.DataLoader(dataset=dataset_val, batch_size=batch_size, num_workers=0, collate_fn=collate, shuffle=False, pin_memory=True)
but results are shown below.
https://colab.research.google.com/drive/1m5VXu-NyQHSRAWtDDzdDs_NwWGH2unI8

**Comment by chenwydj** [comment]
Hi KiyoKando,

1. Could you print the sizes of those variables and compare with mine?
2. I just updated the requirements.txt. You could try to install the specific versions of some libraries.
3. Typically people met killed dataloader when they set workers > 0. I found [an answer here](https://github.com/pytorch/pytorch/issues/8976#issuecomment-481442240). Maybe you could take a look if there is any "shared memory" setting for co-lab?

**Comment by KiyoKando** [comment]
Thank you very much for your patience and help, Wuyang.
I tried as following.

1. Following your guide, I could print the results below
It seems torch.size([6, 127, 127, 3])  contains extra 3.
Is it occurring 96774*3? 
https://colab.research.google.com/drive/1hLHt2R4ZS_AQXD4MkP2SV8bmJmk6cX-I

-helper.py
outputs_global.size()
torch.Size([6, 7, 127, 127])
labels_glb.size()
torch.Size([6, 127, 127, 3])

-loss.py
probs.size()
torch.Size([96774, 7])
target.size()
torch.Size([290322, 7])


2. Thanks for your update but I faced some errors on it.
since I had some error with new requirements like below, 
https://colab.research.google.com/drive/1KpjTtegwXHTvqXFpaMtorqu3e3c-uPV-
https://colab.research.google.com/drive/1LW1MGiKuvQ7h8MPaRGc0KN9UBqRUTH7w

therefore I arranged some of it to just avoid errors.
numpy
torch==1.1.0
torchvision==0.3.0
tqdm
tensorboardX
Pillow
opencv-python==3.4.4.19

but I still have same error on training & evaluating with this new requiements.txt.
https://colab.research.google.com/drive/1U80udIb2xOBGJGauzU8BkGeoxXgvpF9I
https://colab.research.google.com/drive/1PHaexqxDpTE23zT6R-MdbOrfmWilQL27


3. I searched if co-lab has an extra GPU. But seems not to have that yet.

**Comment by chenwydj** [comment]
1. You could consider debugging inside the `train()` function [here](https://github.com/TAMU-VITA/GLNet/blob/master/helper.py#L287) to see when the extra dim ("3") is appended into `labels_glb `.
2. For the problem of the job being killed, maybe you want to monitor the resource consumptions on your virtual machine (`htop` for example) to see if any cpu/swap memory limit is achieved.

**Comment by KiyoKando** [comment]
Thank you for your help, Wuyang!

Now, after converted labels RGB to L, I get proper torch size!
torch.Size([6, 7, 127, 127])
torch.Size([6, 127, 127])
torch.Size([96774, 7])
torch.Size([96774, 7])

For above, I added two lines right after L293:
https://github.com/TAMU-VITA/GLNet/blob/master/helper.py#L293

for labels in range(len(labels_glb)):
            labels_glb[labels] = labels_glb[labels].convert('L')

But, now I face “RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED error.”
I tried recent & former requirement.txt but both of them had the same error.
Also, checked GPU memory seems not full.

details:
https://colab.research.google.com/drive/18z121AjYFoPo7oT4HmoEZZHHSY8DH3Hk

I'd appreciate it if I could get a further clue.
Thank you.

**Comment by chenwydj** [comment]
You could try to comment out these two lines where the `cudnn.deterministic` feature is enabled.
https://github.com/TAMU-VITA/GLNet/blob/a8132640772e4ed3f6ea29a3ab03dc467df2fb66/train_deep_globe.py#L25
https://github.com/TAMU-VITA/GLNet/blob/a8132640772e4ed3f6ea29a3ab03dc467df2fb66/helper.py#L19

**Comment by KiyoKando** [comment]
Thank you for the clue. But the error seems the same.
I suppose it is because of cuda and cdnn incompatibility.
could you tell me which versions do you use?

---
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

!cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 3

**Comment by chenwydj** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 3
#define CUDNN_PATCHLEVEL 1

**Comment by KiyoKando** [comment]
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Sep__1_21:08:03_CDT_2017
> Cuda compilation tools, release 9.0, V9.0.176
> 
> #define CUDNN_MAJOR 7
> #define CUDNN_MINOR 3
> #define CUDNN_PATCHLEVEL 1

Thank you. But it seems unavailable to change version of them on google colab. Do you have any suggestions on preferable environments?

**Comment by chenwydj** [comment]
Maybe you could try to re-install the pytorch to match the cuda version on your system, i.e., choose the pytorch version specifically for cuda10 (as shown by your `nvcc --version`)
https://pytorch.org/get-started/previous-versions/

**Comment by chenwydj** [comment]
This is potentially a platform-related issue. Please re-open if further help is needed.

**Comment by GeneralLi95** [comment]
@KiyoKando Have you make it clear that is this a platform-related issue or something else wrong. I have the same problem.
