### ISSUE TITLE
multigpu training

### ISSUE THREAD

**Issue by sdsy888** [TAMU-VITA/GLNet#15]
Hi, in the `global2local` training process,  I found if I use 2 GPUs, the data will be assigned equally to 2 GPUs along the batch dimension, but the global feature won't divide, thus the `feature concat` won't work properly. 

I think maybe because the global branch only does the [feature extraction work](https://github.com/TAMU-VITA/GLNet/blob/520f0073f673672030f9e4cf67c0c86d389fbf31/models/fpn_global_local_fmreg_ensemble.py#L451-L459)?

In the lines above, I found when I use 2 GPUs, the local feature will be `[n/2, c, h, w]`, while the global will be `[n, c, h, w]`

Is there somewhere I should modify the code for the data-parallel? Thank you!

**Comment by chenwydj** [comment]
Hi Neo Song,

I think multi-gpu training/inference is tricky:
1) Local patches in each mini-batch come from the same global image. That means in each forward pass in `global2local` process, the global branch will only take a single global image (whose features will be utilized by the local branch), while the local branch will take multiple image patches. You probably have to copy the global feature to the other GPU.
2) Here we need some non-tensor data (`top_lefts` and `ratio`) during the forward. These data are not automatically distributed to multi-gpus, and you have to manually handle them in each gpu.

Therefore, I think it may take quite an effort to modify the code to run on multi-gpus.

**Comment by sdsy888** [comment]
> Hi Neo Song,
> 
> I think multi-gpu training/inference is tricky:
> 
> 1. Local patches in each mini-batch come from the same global image. That means in each forward pass in `global2local` process, the global branch will only take a single global image (whose features will be utilized by the local branch), while the local branch will take multiple image patches. You probably have to copy the global feature to the other GPU.
> 2. Here we need some non-tensor data (`top_lefts` and `ratio`) during the forward. These data are not automatically distributed to multi-gpus, and you have to manually handle them in each GPU.
> 
> Therefore, I think it may take quite an effort to modify the code to run on multi-gpus.

Thank you for your reply!
Yes, you are right, I also think that's a "little bit" tricky. 
By the way, just out of curiosity, I found you use data-parallel [here](https://github.com/TAMU-VITA/GLNet/blob/master/helper.py#L171), so you didn't use more than one GPU in training neither?

**Comment by chenwydj** [comment]
I attempted to use multi-gpu when preparing this work but failed, and also the [pretrained checkpoints](https://github.com/TAMU-VITA/GLNet#evaluation) were prepared with the `DataParallel wrappers` turned on. Therefore I kept the `DataParallel wrapper` in the code for compatibility.

**Comment by sdsy888** [comment]
> in the code for compatibility.

Got it, thank you! 
Appreciate your reply~
