### ISSUE TITLE
Can you provide more info on Training & Prediction

### ISSUE THREAD

**Issue by deepseek** [TAMU-VITA/GLNet#4]
Thank you for your hard work,

Can you provide more information on how to train and ow to predict.

**Comment by lamhoangtung** [comment]
+1 upvote for this

**Comment by chenwydj** [comment]
Hi! We updated the instructions for training and evaluation in the Readme, and also uploaded the pretrained model for the Deep Globe. Please take a look and give a try! :)

**Comment by deepseek** [comment]
Thank, should have a look.
